name: Create Release on PR Merge

on:
  push:
    branches:
      - feat/boraquebora

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v6
        with:
          FILES: |
            CHANGELOG
      
      - name: check Diff
        id: checkDiff
        run: |
          echo $GIT_DIFF
      
      - name: Read VERSION file
        id: version
        run: |
          cat VERSION
          exit 2

      - name: Create Git Tag
        id: create_tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        id: create_github_release
        run: |
          gh release create $TAG_NAME -F - <<<"$COMMIT_MESSAGES"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
