name: Create Release on PR Merge

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read VERSION file
        id: version
        run: |
          cat VERSION
        continue-on-error: true

      - name: Get PR commit messages
        id: pr_commit_messages
        run: |
          COMMIT_MESSAGES=$(git log --merges --pretty=format:"- %s" $(git merge-base HEAD $(git rev-parse --abbrev-ref HEAD))..HEAD)
          echo "::set-output name=commit_messages::$COMMIT_MESSAGES"
        continue-on-error: true

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=$(cat VERSION)
          COMMIT_MESSAGES=$(git log --merges --pretty=format:"- %s" $(git merge-base HEAD $(git rev-parse --abbrev-ref HEAD))..HEAD)
          echo "Creating a release with tag $TAG_NAME and release notes:"
          echo "$COMMIT_MESSAGES"
          echo "::set-output name=tag::$TAG_NAME"
          echo "::set-output name=release_notes::$COMMIT_MESSAGES"
        continue-on-error: true
      

      - name: Create Git Tag
        id: create_tag
        run: |
          git tag ${{ steps.create_release.outputs.tag }}
          git push origin ${{ steps.create_release.outputs.tag }}

      - name: Create GitHub Release
        id: create_github_release
        run: |
          gh release create ${{ steps.create_release.outputs.tag }} -F - <<<"${{ steps.create_release.outputs.release_notes }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
